name = "Product Reviews"
client_id = "b3aa63efab132571c2c9f2de3a8dbb6c"
application_url = "https://shopifyreview.it3.in"
embedded = true

[access_scopes]
scopes = "read_products,read_orders,read_customers"

[auth]
redirect_urls = [
  "https://shopifyreview.it3.in/auth/callback"
]

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "/webhooks"

[[webhooks.subscriptions]]
topics = ["orders/fulfilled", "fulfillments/create"]
uri = "/webhooks"

[app_proxy]
url = "https://shopifyreview.it3.in/api/public"
subpath = "shopify-review"
prefix = "apps"
