client_id = "YOUR_SHOPIFY_API_KEY"
name = "Shopify Review"
application_url = "https://example.ngrok.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[access_scopes]
scopes = "read_products,read_orders,read_customers"

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
topics = ["app/uninstalled", "orders/create", "fulfillments/create"]
uri = "/webhooks"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "/webhooks"

[app_proxy]
url = "https://example.ngrok.app/api/public"
subpath = "shopify-review"
prefix = "apps"
